### PR TITLE
SWC-55: switched from GitPython to pygit2

### PR DESCRIPTION
**Pull request by Yousef-1022**
Changed the code structure to utilitze pygit2 instead of GitPython, as GitPython requires Git to be installed on the host system, as well as the installation of git as a third party component counts as forcing the customer to download it.

### CODE REVIEW

**Comment by Yousef-1022** [comment]
Please note, the checks were not successful due to an unpatched fix. The fix was successfully implemented on [SWC-47/API_testing] branch, merging both branches will resolve the issue.

**Review by aldokimi — APPROVED** [review]
All looks good, we still have to create the API end point to send the history data to the UI

**Review by aldokimi — APPROVED** [review]
Now we have an endpoint that sends the data of the changes history to the UI

**Review by aldokimi — APPROVED** [review]
All is working as intended, well done!

**Comment by Yousef-1022** [comment]
I see it too, well done for following the steps in the ticket itself! This branch is ready to go!

**Pull request merged**
